name: C/C++ CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: setup_boost
      run: sudo apt-get install libboost-all-dev
    
    - name: setup_google_test
      run: ./setup_google_benchmark.sh
    
    - name: build
      run: ./build.sh
      
    - name: Run
      run: ./File_Protector
